version: "3.8"
services: 

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data_mariadb:/var/lib/mysql
    networks:
      - my_net
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - my_net
    volumes:
      - data_word:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWD: ${WP_ADMIN_PASSWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on: 
      - wordpress
      - redis
      - adminer
      - portfolio
      - cadvisor
    ports:
      - 443:443
    volumes:
      - data_word:/var/www/html
    networks:
      - my_net
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    volumes:
      - data_word:/var/www/html
    networks:
      - my_net
    restart: always
  adminer:
    depends_on:
      - wordpress
    build: ./requirements/bonus/adminer
    container_name: adminer
    volumes:
      - data_word:/var/www/html
    networks:
      - my_net
    restart: always
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}
    networks:
      - my_net
    restart: always
    volumes:
      - data_word:/var/www/html
  portfolio:
    build: ./requirements/bonus/portfolio
    container_name: portfolio
    networks:
      - my_net
    volumes:
      - data_word:/var/www/html
    restart: always
  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    image: cadvisor
    networks:
      - my_net
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always


networks:
  my_net:
    driver: bridge

volumes:
  data_word:
    driver_opts:
      o: bind 
      type : none
      device: /home/bchifour/data/wordpress
  data_mariadb:
    driver_opts:
      o: bind 
      type : none
      device: /home/bchifour/data/mariadb
